.TH "HAKUTEST\-IMPORT" "1" "2023-12-22" "github.com/shelepuginivan/hakutest" "Hakutest Manual"

.nh
.ad l

.SH "NAME"
hakutest\-import \- import test files.

.SH "SYNOPSIS"
hakutest import [\fItest\-file\fR]

.SH "DESCRIPTION"
Import test file to the Hakutest tests directory specified in the configuration file. This command is essentially an alternative to manually copying a file to the tests directory.

.SH "OPTIONS"
.PP
test\-file
.RS 4
Path to the test file to be imported.
.RE

.SH "EXAMPLES"
.PP
$ hakutest import ~/Downloads/mytest.json
.RS 4
Import test file \fBtest.json\fR located in the \fB~/Downloads\fR directory.
.RE

.SH "SEE ALSO"
\fBhakutest-config\fR(1), \fBhakutest-configuration\fR(7)
