.TH "HAKUTEST\-STATISTICS\-GUI" "1" "2024-02-15" "github.com/shelepuginivan/hakutest" "Hakutest Manual"

.nh
.ad l

.SH "NAME"
hakutest\-statistics\-gui \- graphical application for exporting test statistics.

.SH "SYNOPSIS"
hakutest-statistics

.SH "DESCRIPTION"
Graphical application for exporting test statistics.

Essentially, it is a graphical interface for the \fBhakutest-statistics\fR(1) command.

It allows to select the test, export format, and the directory where the statistics will be exported.

.SH "SEE ALSO"
\fBhakutest-statistics\fR(1)
