.TH "HAKUTEST\-SERVER" "1" "2024-01-12" "github.com/shelepuginivan/hakutest" "Hakutest Manual"

.nh
.ad l

.SH "NAME"
hakutest\-server \- start hakutest server.

.SH "SYNOPSIS"
hakutest server

.SH "DESCRIPTION"
Start Hakutest server on the specified \fBport\fR.

Hakutest web pages, including the test page and test editor, require a running server.

.SH "OPTIONS"
.SS \-p|\-\-port
The port on which server is started. Must be an integer in the range 1024 to 65535. The server will be started on the port specified in the configuration file by default.

.SH "EXAMPLES"
.PP
$ hakutest server
.RS 4
Start Hakutest server on the port specified in the configuration file.
.RE
.PP
$ hakutest server \-\-port 3000
.RS 4
Start Hakutest server on port 3000.
.RE

.SH "SEE ALSO"
\fBhakutest-config\fR(1), \fBhakutest\-configuration\fR(5)
