.TH "HAKUTEST\-SERVER\-APPLET" "1" "2024-02-15" "github.com/shelepuginivan/hakutest" "Hakutest Manual"

.nh
.ad l

.SH "NAME"
hakutest\-server\-applet \- start hakutest server with a systray applet.

.SH "SYNOPSIS"
hakutest-server

.SH "DESCRIPTION"
Start Hakutest server with a systray applet.

Hakutest web pages, including the test page and test editor, require a running server.

When the executable is running, an icon is displayed in the system tray. It can be used to stop the server.

The server will be started on the port specified in the \fBhakutest-configuration\fR(5).

.SH "SEE ALSO"
\fBhakutest-config\fR(1), \fBhakutest-configuration\fR(5), \fBhakutest-server\fR(1)
