.TH "HAKUTEST\-HELP" "1" "2023-12-22" "github.com/shelepuginivan/hakutest" "Hakutest Manual"

.nh
.ad l

.SH "NAME"
hakutest\-help \- show help message.

.SH "SYNOPSIS"
hakutest help [\fIcommand\fR]

.SH "DESCRIPTION"
Provide help for any command in the application.

.SH "OPTIONS"
.SS command
Сommand about which you want to see the help message.

.SH "EXAMPLES"
.PP
$ hakutest help
.RS 4
Provide help information about the program.
.RE
.PP
$ hakutest help config
.RS 4
Provide help information about \fBhakutest-config\fR(1) command.
.RE
