.TH "HAKUTEST\-COMPLETION" "1" "2023-12-22" "github.com/shelepuginivan/hakutest" "Hakutest Manual"

.nh
.ad l

.SH "NAME"
hakutest\-completion \- generate hakutest completion scripts.

.SH "SYNOPSIS"
hakutest completion [\fIbash\fR|\fIzsh\fR|\fIfish\fR|\fIpowershell\fR]

.SH "DESCRIPTION"
Generate Hakutest autocompletion scripts for the specified shell. It prints generated script to the standard output.

.SH "OPTIONS"
.SS bash|zsh|fish|powershell
Shell for which the autocompletion script is generated.

.SH "EXAMPLES"
.PP
$ hakutest completion zsh
.RS 4
Generate zsh autocompletion script.
.RE
.PP
$ hakutest completion bash > _hakutest
.RS 4
Generate bash autocompletion script and write it to the file.
.RE
.PP
$ source <(hakutest completion bash)
.RS 4
Generate bash autocompletion script and immediately apply completions.
.RE
