# **`tests_directory` and `results_directory` depends on the settings of
# your operating system. Please set them manually.**
#
general:
    # tests_directory:
    # results_directory:
    show_results: true
    overwrite_results: false
server:
    port: 8080
    mode: release
