.TH "HAKUTEST\-STATISTICS" "1" "2023-12-23" "github.com/shelepuginivan/hakutest" "Hakutest Manual"

.nh
.ad l

.SH "NAME"
hakutest\-statistics \- export test results statistics.

.SH "SYNOPSIS"
hakutest statistics <\fItest-name\fR> [\fIformat\fR]

.SH "DESCRIPTION"
Export test results statistics to different formats.

.SH "OPTIONS"
.PP
test-name
.RS 4
Name of the test results folder (i.e. its file name) which statistics you want to export.
.RE
.PP
format
.RS 4
Format of the statistics data export. Currently, formats \fBexcel\fR and \fBimage\fR are supported.

\- \fBexcel\fR produces an Excel spreadsheet with points, scored by students, and correctness of every submitted answer.
.br
\- \fBimage\fR produces a student performance histogram.

If the second argument is not provided, command prints table with scored points to the standard output. The table contains students, their scores, and the percentage of correct answers.
.RE

.SH "EXAMPLES"
.PP
$ hakutest statistics my\-test
.RS 4
Print statistics of the test \fBmy\-test\fR to the standard output.
.RE
.PP
$ hakutest statistics my\-test excel
.RS 4
Generate Excel spreadsheet with statistics of the test \fBmy\-test\fR.
.RE
.PP
$ hakutest statistics my\-test image
.RS 4
Generate student performance histogram of the test \fBmy\-test\fR.
.RE

.SH "SEE ALSO"
\fBhakutest-config\fR(1), \fBhakutest-configuration\fR(7), \fBhakutest-results\fR(7)
